name: Daily Monitoring Stage

on:
  schedule:
    - cron: "0 04 * * 1-5"
    
permissions:
  id-token: write
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: daily monitoring stage

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/checkout@v3
    - name: Setup python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
      
    - name: Install python requirements        
      run: pip install -r requirements.txt
    - run: py.test --environment Staging



