name: Deployment tests

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment on which we deploy'
        default: 'stage'
        required: true
        type: string

  workflow_call:
    inputs:
      env:
        description: 'Environment on which we deploy'
        default: 'stage'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: Deployment test suite execution

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/checkout@v3
    - name: Setup python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install python requirements
      run: pip install -r requirements.txt
    - run: py.test --environment Staging

